name: Generate Build
on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: 'Which build to generate'
        options:
          - Android
          - MacOS
          - Web
        required: true

jobs:
  build:
    runs-on: ${{ inputs.name == 'MacOS' && 'macos-latest' || 'ubuntu-latest' }}
    steps:
      - name: Build
        run: echo "Generating build for ${{ github.event.inputs.name }} on $RUNNER_OS"
